# generic bindings
# atc
def decode_atc_rgb4(data: bytes, width: int, height: int) -> bytes: ...
def decode_atc_rgba8(data: bytes, width: int, height: int) -> bytes: ...

# astc
def decode_astc_4_4(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_5_4(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_5_5(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_6_5(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_6_6(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_8_5(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_8_6(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_8_8(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_10_5(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_10_6(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_10_8(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_10_10(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_12_10(data: bytes, width: int, height: int) -> bytes: ...
def decode_astc_12_12(data: bytes, width: int, height: int) -> bytes: ...

# bcn
def decode_bc1(data: bytes, width: int, height: int) -> bytes: ...
def decode_bc3(data: bytes, width: int, height: int) -> bytes: ...
def decode_bc4(data: bytes, width: int, height: int) -> bytes: ...
def decode_bc5(data: bytes, width: int, height: int) -> bytes: ...
def decode_bc6_signed(data: bytes, width: int, height: int) -> bytes: ...
def decode_bc6_unsigned(data: bytes, width: int, height: int) -> bytes: ...
def decode_bc7(data: bytes, width: int, height: int) -> bytes: ...

# etc
def decode_etc1(data: bytes, width: int, height: int) -> bytes: ...
def decode_etc2_rgb(data: bytes, width: int, height: int) -> bytes: ...
def decode_etc2_rgba1(data: bytes, width: int, height: int) -> bytes: ...
def decode_etc2_rgba8(data: bytes, width: int, height: int) -> bytes: ...
def decode_eacr(data: bytes, width: int, height: int) -> bytes: ...
def decode_eacr_signed(data: bytes, width: int, height: int) -> bytes: ...
def decode_eacrg(data: bytes, width: int, height: int) -> bytes: ...
def decode_eacrg_signed(data: bytes, width: int, height: int) -> bytes: ...

# pvrtc
def decode_pvrtc_2bpp(data: bytes, width: int, height: int) -> bytes: ...
def decode_pvrtc_4bpp(data: bytes, width: int, height: int) -> bytes: ...

# crunch
def decode_crunch(data: bytes, width: int, height: int) -> bytes: ...
def decode_unity_crunch(data: bytes, width: int, height: int) -> bytes: ...

# custom bindings
def decode_astc(
    data: bytes, width: int, height: int, block_width: int, block_height: int
) -> bytes: ...
